apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-server
  namespace: etcd
spec:
  secretName: etcd-server-secret
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  commonName: etcd-server
  dnsNames:
    - etcd-server
    - etcd-server.etcd.svc
    - etcd-server.etcd.svc.cluster.local
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: etcd-ca
    kind: ClusterIssuer
