apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client
  namespace: etcd
spec:
  secretName: etcd-client-secret
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  commonName: etcd-client
  dnsNames:
    - etcd-client
  usages:
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: etcd-ca
    kind: ClusterIssuer