apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-ca
  namespace: etcd
spec:
  commonName: etcd-ca
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  secretName: etcd-ca-secret
  usages:
    - digital signature
    - key encipherment
    - cert sign
  issuerRef:
    name: cert-manager-ca
    kind: ClusterIssuer