apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prod
  name: hawkeye-role
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hawkeye-role-binding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: hawkeye-release
  namespace: prod
roleRef:
  kind: Role
  name: hawkeye-role
  apiGroup: rbac.authorization.k8s.io
