replicaCount: 1

image:
  repository: ccr.ccs.tencentyun.com/tianzx/hawkeye
  pullPolicy: IfNotPresent

# imagePullSecrets:
#   - name: k3sdeploykey

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 1000m 
    memory: 2000Mi

serviceAccount:
  create: true
  name: hawkeye-release


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80 
