replicaCount: 1

image:
  repository: ccr.ccs.tencentyun.com/tianzx/hawkeye
  pullPolicy: IfNotPresent

# imagePullSecrets:
#   - name: k3sdeploykey

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 300m 
    memory: 900Mi

serviceAccount:
  create: true
  name: hawkeye-release


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80 
