replicaCount: 1

image:
  repository: ccr.ccs.tencentyun.com/tianzx/hawkeye
  pullPolicy: IfNotPresent

# imagePullSecrets:
#   - name: k3sdeploykey

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m  
    memory: 1000Mi

serviceAccount:
  create: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80 
