global:
  name: consul
  datacenter: dc1
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token

server:
  replicas: 3
  bootstrapExpect: 3
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  storage: 10Gi
  connect: true

client:
  enabled: true
  grpc: true

ui:
  enabled: true
  service:
    enabled: true
    type: 'ClusterIP'

connectInject:
  enabled: true

