apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: combined-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - ai-finance-istio-gateway
  http:
    - name: ai-finance
      match:
        - uri:
            prefix: /hawkeye/
      rewrite:
        uri: /
      route:
        - destination:
            host: hawkeye-release.prod.svc.cluster.local
            port:
              number: 80
    - name: argocd
      match:
        - uri:
            prefix: /
      rewrite:
        uri: /argo-cd/
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
