apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: combined-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - ai-finance-istio-gateway
  http:
    - name: ai-finance
      match:
        - uri:
            prefix: /hawkeye/
      rewrite:
        uri: /
      delegate:
        name: hawkeye-release
        namespace: prod
    - name: grafana
      match:
        - uri:
            exact: /grafana
        - uri:
            prefix: /grafana/
      rewrite:
        uri: /
      route:
        - destination:
            host: loki-grafana.loki.svc.cluster.local
            port:
              number: 80