apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ai-finance-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - ai-finance-istio-gateway
  http:
    - match:
        - uri:
            prefix: /hawkeye/
      rewrite:
        uri: /
      route:
        - destination:
            host: hawkeye-release.prod.svc.cluster.local
            port:
              number: 80