apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - ingressgateway
  http:
  - route:
    - destination:
      host: api-service 
      port:
        number: 80
      none: true    # 使用 none 类型的 backend
  # - match:
  #   - uri:
  #       prefix: /api
  #   route:
  #   - destination:
  #       host: api-service
  #       port:
  #         number: 80
