apiVersion: networking.istio.io/v1beta1  
kind: VirtualService
metadata:
  name: api-virtualservice
spec:
  hosts:
  - "*"   
  gateways:  
  - ingressgateway  
  http:   
  - route:  
  - destination:    
      subset: none