gateways:
    - ai-finance-istio-gateway
  http:
    - name: ai-finance
      match:
        - uri:
            prefix: /hawkeye/
      rewrite:
        uri: /
      route:
        - destination:
            host: hawkeye-release.prod.svc.cluster.local
            port:
              number: 80
    - name: grafana
      match:
        - uri:
            exact: /grafana
        - uri:
            prefix: /grafana/
      rewrite:
        uri: /
      route:
        - destination:
            host: loki-grafana.default.svc.cluster.local
            port:
              number: 80