apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: combined-virtualservice
spec:
  hosts:
    - "42.192.1.41"
    - "ai-finance.cloud"
  gateways:
    - ai-finance-istio-gateway
    - mesh
  http:
    - name: ai-finance
      match:
        - uri:
            prefix: /hawkeye/
      rewrite:
        uri: /
      delegate:
        name: hawkeye-release
        namespace: prod
    - name: grafana
      match:
        - uri:
            exact: /grafana
        - uri:
            prefix: /grafana/
      rewrite:
        uri: /
      route:
        - destination:
            host: loki-grafana.loki.svc.cluster.local
            port:
              number: 80
    - name: kiali
      match:
        - uri:
            exact: /kiali
        - uri:
            prefix: /kiali/
      rewrite:
        uri: /kiali/
      route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001
    - name: consul-ui
      match:
        - uri:
            prefix: /consul/
            prefix: /v1/
      route:
        - destination:
            host: consul-ui.consul.svc.cluster.local
            port:
              number: 80
      headers:
        request:
          set:
            X-Forwarded-Path: /consul
            X-Forwarded-Prefix: /consul
    - name: consul-ui-assets
      match:
        - uri:
            prefix: /consul/ui/
      route:
        - destination:
            host: consul-ui.consul.svc.cluster.local
            port:
              number: 80