apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: combined-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - ai-finance-istio-gateway
  http:
    - name: ai-finance
      match:
        - uri:
            prefix: /hawkeye/
      rewrite:
        uri: /
      route:
        - destination:
            host: hawkeye-release.prod.svc.cluster.local
            port:
              number: 80
    - name: grafana
      match:
        - uri:
            exact: /grafana
        - uri:
            prefix: /grafana/
      rewrite:
        uri: /
      route:
        - destination:
            host: loki-grafana.loki.svc.cluster.local
            port:
              number: 80
    # - name: weave-gitops
    #   match:
    #     - uri:
    #         exact: /weave-gitops
    #     - uri:
    #         prefix: /weave-gitops/
    #   rewrite:
    #     uri: /
    #   route:
    #     - destination:
    #         host: ww-gitops-weave-gitops.flux-system.svc.cluster.local
    #         port:
    #           number: 9001