apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: default-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - ingressgateway
  http:
  - route:
    - destination:
        host: placeholder-service
