loki:
  enabled: true
  isDefault: true
  url: http://loki.loki:3100
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki.loki:3100/loki/api/v1/push
grafana:
  enabled: true
  env:
    GF_SERVER_ROOT_URL: "http://42.192.1.41/grafana/"
    GF_SERVER_SERVE_FROM_SUB_PATH: false
  image:
    tag: latest
