apiVersion: v1
kind: Service
metadata:
  name: weave-gitops-nodeport
  namespace: flux-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/instance: ww-gitops
  ports:
    - protocol: TCP
      port: 9001
      nodePort: 30080