on:
    push:
      branches:
        - main
jobs:
    release:
      runs-on: ubuntu-latest
      # permissions:
      #   contents: read
      #   packages: write
      #   id-token: 'write'
      #   issues: 'write' #__This fixed the HttpError: Resource not accessible by integration
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
  
        - name: Configure Git
          run: |
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            
        - name: Install Helm
          uses: azure/setup-helm@v1

        - name: Run chart-releaser
          uses: helm/chart-releaser-action@v1.5.0
          env:
            CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            